plugins {
    id 'java'
    id 'application'
}

group = 'ch.bzz'
version = '1.0-SNAPSHOT'

application {
    mainClass = 'ch.bzz.LibraryAppMain'
}

run {
    standardInput = System.in
}

repositories {
    mavenCentral()
}

dependencies {
    // dependencies for the application
    implementation 'org.postgresql:postgresql:42.7.3'

    // dependencies for testing
    testImplementation 'org.junit.jupiter:junit-jupiter:5.10.2'
}

test {
    useJUnitPlatform()
}
